<?php

/**
 * This file is automatically generated. Use 'bin/celerity map' to rebuild it.
 *
 * @generated
 */
return array(
  'names' => array(
    'js/o3dv.min.js' => 'be65c76b',
    'js/stlview.js' => '5a3cc733',
  ),
  'symbols' => array(
    'javelin-behavior-aviv-stl-viewer' => '5a3cc733',
    'online_3d_viewer' => 'be65c76b',
  ),
  'requires' => array(
    '5a3cc733' => array(
      'online_3d_viewer',
    ),
  ),
  'packages' => array(),
);
