<?php

/**
 * This file is automatically generated. Use 'bin/celerity map' to rebuild it.
 *
 * @generated
 */
return array(
  'names' => array(
    'externals/o3dv.min.js' => '55f595ca',
    'js/stlview.js' => '2b9853b0',
  ),
  'symbols' => array(
    'javelin-behavior-aviv-stl-viewer' => '2b9853b0',
    'online_3d_viewer' => '55f595ca',
  ),
  'requires' => array(
    '2b9853b0' => array(
      'online_3d_viewer',
    ),
  ),
  'packages' => array(),
);
