<?php

/**
 * This file is automatically generated. Use 'bin/celerity map' to rebuild it.
 *
 * @generated
 */
return array(
  'names' => array(
    'js/stlview.js' => '5b4a5355',
  ),
  'symbols' => array(
    'javelin-behavior-aviv-stl-viewer' => '5b4a5355',
  ),
  'requires' => array(),
  'packages' => array(),
);
