<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 *
 * @generated
 * @phutil-library-version 2
 */
phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' => array(
    'StlViewApplication' => 'application/StlViewApplication.php',
    'StlViewCelerityResources' => 'celerity/StlViewCelerityResources.php',
    'StlViewDocEngine' => 'engineextension/StlDocEngine.php',
    'StlViewHacksController' => 'controller/StlViewHacksController.php',
  ),
  'function' => array(),
  'xmap' => array(
    'StlViewApplication' => 'PhabricatorApplication',
    'StlViewCelerityResources' => 'CelerityResourcesOnDisk',
    'StlViewDocEngine' => 'PhabricatorDocumentEngine',
    'StlViewHacksController' => 'PhabricatorController',
  ),
));
